Featured methods
AlfredoElizarraras/ruby-my-enumerables pull request #1
Opened 2020-02-21 15:42 UTC by AlfredoElizarraras

Finish project with Odin project specifications by the following:

  

1.   Create #my_each, a method that is identical to #each but (obviously) does not use #each. You’ll need to remember the yield statement. Make sure it returns the same thing as #each as well.
2.     Create #my_each_with_index in the same way.
3.     Create #my_select in the same way, though you may use #my_each in your definition (but not #each).
4.     Create #my_all? (continue as above)
5.     Create #my_any?
6.     Create #my_none?
7.     Create #my_count
8.     Create #my_map
9.     Create #my_inject
10.     Test your #my_inject by creating a method called #multiply_els which multiplies all the elements of the array together by using #my_inject, e.g. multiply_els([2,4,5]) #=> 40
11.     Modify your #my_map method to take a proc instead.
12.     Modify your #my_map method to take either a proc or a block. It won’t be necessary to apply both a proc and a block in the same #my_map call since you could get the same effect by chaining together one #my_map call with the block and one with the proc. This approach is also clearer, since the user doesn’t have to remember whether the proc or block will be run first. So if both a proc and a block are given, only execute the proc.

2020-02-23 04:21 UTC, fatymahmed requested changes
### Hi @AlfredoElizarraras,
Great job so far, just a few more changes to go 👏👏.
- [x] The screenshots in your README file lead to a broken link, I suggest you remove them or change them. Since you don't have a live link, remove that section in the README file.
- [x] Do not make any changes in the stickler config files, use the ones provided by microverse, check [here](https://github.com/microverseinc/linters-config/tree/master/ruby) see [screenshot of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png).
You can disable some rules when they are absolutely necessary in the source code. See below:
   

>  Style/CaseEquality cop can be disabled as described here https://rubydoc.info/gems/rubocop/0.24.1/frames#Disabling_Cops_within_Source_Code [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/style_case_equality.png) from Pathwright

- [x] You should not have any debugging instructions in committed code [as discussed here](https://questions.microverse.org/t/debugging-instructions-code/346), see screenshot [ of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/section/debugging_requirement.png)

- Check my comments below for a detailed review of your enumerable methods. Check out the enumerable methods [here](https://ruby-doc.org/core-2.6.5/Enumerable.html) and all the different arguments that can be passed to each of them.

### Kindly make the suggested changes then request for another code review.

## Status: Changes Required 🛑
_Feel free to reach out to me on slack (Fatima) if you have any questions, I'd be happy to help_

2020-02-23 04:30 UTC, fatymahmed commented on public/main.rb
> +  end
- [ ] For my_all? let's handle the case when no block or argument is given, it returns true when none of the collection members are false or nil.
  For example

The built-in method
`[1, true, 'hi', []].all?`
returns `true`

Your method
`1, true, 'hi', []].my_all?`
returns `false`

2020-02-23 04:33 UTC, fatymahmed commented on public/main.rb
> +  end
- For my_any? handle the case when no block or argument is given returns true if at least one of the collections is not false or nil.

For example

The built-in method
`>> [nil, false, true, [ ] ].any?
=> true
`

Your method
`>> [nil, false, true, [ ] ].my_any?
=> false
`
- It should return true since one element in the array is true

2020-02-23 04:40 UTC, fatymahmed commented on public/main.rb
> +  end
- Handle the case when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
For example

The built-in method
`>> %w[cat door rod blade].any?('cat')
=> true
`

Your method
`>> [%w[cat door rod blade].my_any?('cat')
=> false
`
- It should return true since one element in the array matches the pattern

2020-02-23 04:46 UTC, fatymahmed commented on public/main.rb
> +  end
- For my_none? handle cases when no block or argument is given returns true only if none of the collection members is true


For example
Built-in method
`[nil, false, true, []].none?` returns `false`

Your method
`[nil, false, true, []].none?` returns `true`
- It should return false since at least 1 element is true

2020-02-23 04:52 UTC, fatymahmed commented on public/main.rb
> +  end
- Handle cases when a class is passed as an argument, it returns true if none of the collection is a member of such class.
For example
Built-in method
`['hi', 1 ,34, 55].my_none?(String)` returns `false`

Your method
`['hi', 1 ,34, 55].my_none?(String)` returns `true`
- It should return false since at least 1 element is of class String.

2020-02-23 04:57 UTC, fatymahmed commented on public/main.rb
> +  end
- Handle the case when a Regex is passed as an argument, it returns true only if none of the collection matches the Regex
For example
Built-in method
`[%w[dog door rod blade].none?(/d/)` returns `false`

Your method
`%w[dog door rod blade].my_none?(/d/)` returns `true`
- It should return false since at least 1 element matches the Regex.

2020-02-23 05:03 UTC, fatymahmed commented on public/main.rb
> +  end
- Handle the case when a pattern other than Regex or a Class is given, it returns true only if none of the collection matches the pattern


For example
Built-in method
`[5, 'door', 'rod', 'blade'].none?(5)` returns `false`

Your method
`[5, 'door', 'rod', 'blade'].my_none?(5)` returns `true`
- It should return false since at least 1 element matches the pattern.

2020-02-23 05:09 UTC, fatymahmed commented on public/main.rb
> +end
- For my_inject, handle the case when it combines all elements of enum by applying a binary operation, specified by a block.

 For example
 Built-in method
 `Range.new(5, 50).inject(4) { |prod, n| prod * n }` returns    `5069015533618896340602101361010794807396273594826752000000000000`

 Your method
 `Range.new(5, 50).my_inject(4) { |prod, n| prod * n }` returns  `1267253883404724085150525340252698701849068398706688000000000000`
- Make sure your method returns the same value as the built-in one.

2020-02-23 05:19 UTC, fatymahmed commented on public/main.rb
> +end
- handle the case when a symbol is specified combines each element of the collection by applying the symbol as a named method

 For example
 Built-in method
 `Range.new(5, 50).inject(2, :*)` returns    `2534507766809448170301050680505397403698136797413376000000000000`

 Your method
 `Range.new(5, 50).my_inject(2, :*)` returns  `1267253883404724085150525340252698701849068398706688000000000000`
- Make sure your method returns the same value as the built-in one.

2020-02-24 15:09 UTC, AlfredoElizarraras commented on public/main.rb
> +end
Hello, thanks for your code review, I think it's one of the best I have gotten, I did the changes, so hopefully the next submission will be the right one. The only thing I'm not sure about the rubocop Style/For that's asking me to use each instead for so I also disable with the comments in the file and not in the configuration file, so well thanks again.

2020-02-25 09:54 UTC, stratospherique requested changes
### Great work implementing the suggested changes :clap: However, you still have one method to refactor in order to get approval for this project. Check :arrow_down: 

- **[REQUIRED]** Check the code comment below, it should help you refactor your method :nerd_face: 

### That's it :relieved: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-02-25 09:54 UTC, stratospherique commented on public/main.rb
> +  end
* [ ] `my_inject` is identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

* [ ] my_inject combines all elements of enum by applying a binary operation, specified by a block
  ```ruby
    range = Range.new(5, 50)
    p range.my_inject(4) { |prod, n| prod * n } == range.inject(4) { |prod, n| prod * n } # false
  ```

2020-02-25 18:05 UTC, AlfredoElizarraras commented on public/main.rb
> +  end
Hello. Thanks for your cool review, I did the changes to accomplish the method. This time I test it with more cases, and it's working well.

2020-02-26 10:23 UTC, fatymahmed approved these changes
## Hi @AlfredoElizarraras,
### Great job making the suggested changes🎉🎉
### It's a 👍🏾 from me!
## ✔️ Approved!

Good luck with your next projects.
 _Don't forget to submit your project completion form_

2020-02-26 15:07 UTC, AlfredoElizarraras commented
Hello, Thanks for the review and the approve I will merge it then!

2020-02-26 15:08 UTC, merged